Task/es6
idrsolutions/idrsolutions-nodejs-client pull request #10
Opened 2023-05-11 09:35 UTC by josrepo

Updated the NodeJS Client to ES6

2023-05-15 14:41 UTC, Amy1612 approved these changes

2023-05-16 10:33 UTC, KieranFrance approved these changes

2023-05-17 10:35 UTC, leonatherton commented
It's a minor point, but thoughts on switching double quotes back to single quotes?

2023-05-31 10:40 UTC, daniel-warren requested changes
+ 1 on switching double quotes back to single quotes (where applicable).

I also think in making this change, we should also look into adding an [engines](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#engines) section to the package.json?

2023-06-05 15:01 UTC, leonatherton approved these changes

2023-06-05 15:17 UTC, daniel-warren approved these changes

2023-07-20 09:29 UTC, merged