Bugfix/non functional timeout
idrsolutions/idrsolutions-nodejs-client pull request #11
Opened 2023-05-15 09:25 UTC by josrepo

Fixes the timeout not working as the event was not responded to

2023-05-15 14:43 UTC, Amy1612 approved these changes

2023-05-16 10:33 UTC, KieranFrance approved these changes

2023-05-16 10:33 UTC, KieranFrance approved these changes

2023-05-17 10:09 UTC, leonatherton requested changes
What does the user see when a timeout occurs? Does the `error` handler also get called which handles the error?

This updates the POST request, but I believe the polling still needs a fix applied.

2023-06-19 13:36 UTC, josrepo commented
Fix now applied to both requests, tested and is functional.

@leonatherton the error handler is called in both cases

2023-06-19 14:45 UTC, daniel-warren approved these changes

2023-07-18 16:26 UTC, leonatherton approved these changes

2023-07-20 09:28 UTC, merged